version: '3'

services:
    bitcode-nginx:
        image: brammm/bitcode-nginx
        networks:
            - ingress
        labels:
          - "traefik.backend=bitcode-nginx"
          - "traefik.docker.network=ingress"
          - "traefik.frontend.rule=Host:bitcode.be"
          - "traefik.enable=true"
          - "traefik.port=80"
          - "traefik.default.protocol=http"

networks:
  ingress:
    external: true