version: '3'

services:
    bitcode-nginx:
        image: brammm/bitcode-nginx
        networks:
            - web
        labels:
          - "traefik.backend=bitcode-nginx"
          - "traefik.docker.network=web"
          - "traefik.frontend.rule=Host:bitcode.be,b1tc0de.be,b1tc0.de,b1tco.de,bitc0.de"
          - "traefik.enable=true"
          - "traefik.port=80"
          - "traefik.default.protocol=http"
#          - "traefik.frontend.redirect.regex=b1tc0de.be|b1tc0.de|b1tco.de|bitc0.de"
#          - "traefik.frontend.redirect.replacement=https://bitcode.be"
#          - "traefik.frontend.redirect.permanent=true"

networks:
  web:
    external: true