version: '3'

services:
    bitcode-nginx:
        ports:
            - 8080:80
        build:
            context: ./
            dockerfile: docker/nginx/Dockerfile
        image: brammm/bitcode-nginx
        volumes:
            - ./public:/app/public
